import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import styles from '../styles/Home.module.css'

const Main = styled.div`

margin: 0 auto;
width: 100vw;
height: 100vh;
display: flex;
align-items: center;
justify-content: center;
text-align: center;

`;
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Carol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>Teste hospedagem - ✅</h1><br />
        <h1>Teste deploy - ✅</h1>
      </Main>

    </div>
  )
}
